### ISSUE TITLE
patches and development

### ISSUE THREAD

**Issue by urbels** [ticklemynausea/idlerpg#1]
Hi! Are you planing to add those patches and improve them? 
http://idle.quyo.de/patches.php

**Comment by ticklemynausea** [comment]
Hey. Sorry for the late response.

The version of IdleRPG I have here already includes most, if not all, of those patches. There's no reference to that in the history because of last minute half-assed commits and versioning. I planned to start from scratch and add each patch at a single time (together with my own additions and improvements) to have a proper history but I never got around to do it. I'll keep this issue open until I do get around to do it.

I'll add a link to the patches website to the project description to credit the creators. Thanks for your interest.

**Comment by urbels** [comment]
Hey,

Ok, can`t wait for you to finish this. I`m still using the old one. :)

**Comment by urbels** [comment]
Today i noticed you updated yours. Nice job! Btw i used this one. Check auto login part it is improved http://irpg.o-o.lv/botv2.pl
